### ISSUE TITLE
Only returning first 101 issues

### ISSUE THREAD

**Issue by ebiss** [samsmu/JIRA2PM#19]
Hi there! Love using this tool, but the return on my query will only show 100 records, max. Is this a known limitation of the add-on? In JIRA, the same query returned 184 issues.

**Comment by mpkh** [comment]
@ebiss yes, afair it's known limitation of JIRA API

**Comment by ebiss** [comment]
@mpkh Hmm, that will be a blocker for us trying to use this for our metrics. The other resolution is for us to have multiple sheets pulling different queries and then using the ImportRange function to conglomerate the date. Any plans to support > 1 query return?

**Comment by BlackCatter** [comment]
Hi @ebiss , no, it is not known limitation. Currently any request should get up to 1000 jira records. 
Are you using cloud host or self host jira? Can you share your JQL string, so i can try it on my jira server?

**Comment by ebiss** [comment]
@BlackCatter we are using a Cloud instance of JIRA. From what I can tell, other plugins are also hitting the same max of 100. My JQL is:
 labels = "PI#2" AND project in (Uphoria, Dimension, "Data Integrations", "Data Science", "Data Intelligence") AND labels != removed_from_PI

I've also tried opening it up to queries that should return far more and seeing the same cap on results

**Comment by BlackCatter** [comment]
While i am checking, can you also try using button to send request at tab "JIRA2PM :: 3 Display Options"?Request which is send from this tab will be paginated by groups of 200 issues and this is a workaround for getting more than 1000 issues per request

**Comment by ebiss** [comment]
No luck sending the request from that tab

**Comment by BlackCatter** [comment]
Ok, it turns out that cloud hosted jira max issue count per request is 100

I've patched request from "JIRA2PM :: 3 Display Options", they will be now paginated by groups of 100 and will handle max cap of 100 correctly. This changes will be available in about 1 hour - 5 hours. 

Can you try it again later and confirm that it is fixed issue?

**Comment by ebiss** [comment]
I'm still seeing queries getting capped at 100 results, unfortunately. Just to confirm, your patch is on this screen? 
![screen shot 2017-10-02 at 8 31 17 am](https://user-images.githubusercontent.com/22816463/31079737-45f9e904-a74c-11e7-8f7c-3fb4cb6ed4d2.png)

**Comment by ebiss** [comment]
Update: Just tried again, and got the full 192 results! We might be able to close this one out, thanks for the help

**Comment by BlackCatter** [comment]
I'm glad it helped!
